version: '3'

services:
  android:
    container_name: android_builder
    build: .
    volumes:
      - ./androidbuild:/root/android/lineage
    environment:
      - BUILD_NAME=mondrianwifi
      - BRANCH_NAME=lineage-17.1
      - USE_CCACHE=1
      - CCACHE_DIR=/root/android/lineage/.ccache
      - CLEAN_BUILD=0