version: '3'

services:
  android:
    container_name: android_builder
    build:
      context: .
      args:
        UID: 1001

    volumes:
      - ./androidbuild:/home/builder/android/lineage
    environment:
      - BUILD_NAME=mondrianwifi
      - BRANCH_NAME=lineage-17.1
      - USE_CCACHE=1
      - CCACHE_DIR=/home/builder/android/lineage/.ccache
      - CLEAN_BUILD=0

        UID=